### ISSUE TITLE
New API: Fetch specific department json files according to user settings

### ISSUE THREAD

**Issue by OscarWang114** [wasedatime/wasedatime-web#25]
Currently we only support `SILS` `PSE` `CJL` `FSE` `ASE` `CSE` departments. The syllabus of these departments are bundled in **one big** json file `course_list_all.json` in https://wasetime.com/api/static/2018-2019/course_list_all.json

We want to support all departments in the future. We **cannot** bundle all departments into one json file this time since it will be too large and unnecessary. Therefore we need to: 
- [x] 1. Generate a specific json file for each department. This should be done by project `waseda-syllabus-scraper`. 
- [ ] 2. Cache the json files in nginx proxy to boost performance.
- [ ] 3. Checkout cloudflare caching settings as well.
- [ ] 4. Perform stress tests and benchmarking to see if this idea is actually realistic.
- [ ] 5. In project `wasetime-web`, we want to fetch the json files according to the departments selected by the user. We plan to allow users to select up to 5 departments to avoid fetching too much data, which can decrease performance.

**Comment by AustinZhu** [comment]
Solved by #80
