### ISSUE TITLE
[Suggestion] Lighthouse Results

### ISSUE THREAD

**Issue by nissy-dev** [wasedatime/wasedatime-web#3]
Hi, I'm 4th grade of the waseda university studenets.
I'm belonging to the applied chemistry.

I tried to execute Lighthouse about this website.
The result is the following picture.

<img width="1279" alt="2018-04-23 10 23 33" src="https://user-images.githubusercontent.com/17228098/39102710-3c4abbce-46e1-11e8-8beb-60ac11563900.png">

The following URL describe the detail of Lighthouse
[Lighthouse](https://developers.google.com/web/tools/lighthouse/)

The performance and the PWA is not so good.
If you want to provide the better UX, you should try to fix these points.

If you have some motivation to apply the PWA, i may help something!! 
(Just, I'm interested in the PWA, I have no experience about the implementation)

In Japan, the Long Holiday(Golden Week!!) will be coming soon, 
so I have the plan to try to apply the pwa and submit PR. 

How do you think about these suggestion?

**Comment by OscarWang114** [comment]
Hello @nd-02110114! You must be にっしさん from WRESS 😄Welcome to WaseTime!

I think your proposal is fantastic and would welcome a PR for sure.

However, currently, not much documentation is written (I'm sorry for that 😢), so please let me know if you have any problem developing the app locally. I'm having my final exams soon until 5/10, but I will reply as frequently as possible!

I'd like to say thank you again and please enjoy the upcoming golden week!

**Comment by OscarWang114** [comment]
I'll never forget about you 😄 
Life at NUS is crazy. There is so much work here, but the experience is unforgettably awesome. I hope you're doing well as a 4th year Waseda student!
Absolutely. Please let me know if you have any questions. 😆You think you can set up the environment by following the README.

**Comment by AustinZhu** [comment]
![Uploading image.png…]()
