### ISSUE TITLE
Entire site is blank across multiple devices

### ISSUE THREAD

**Issue by tvwolfsnake** [wasedatime/wasedatime-web#411]
## Expected Behavior
Webapp loads

## Actual Behavior
After the website loads, the webapp does not load at all, hanging on a blank white page. This behavior has been consistent since around when v3.2.0 went live—I know because I tried to use the site around that time.

## Steps to Reproduce the Problem
Load the website

## Specifications
- Platform: Chrome version 106.0.5249.79 and Firefox 105.2.0 on Android 12 on Pixel 5a, Firefox 105.0.1 on Windows 11, unknown browser on unknown recent Android version (asked a friend to double-check that it wasn't just a problem with my devices).

**Comment by YHhaoareyou** [comment]
Thanks for your report! We have also noticed the problem and now we are trying to solve it. Sorry for causing your inconvenience!

**Comment by tvwolfsnake** [comment]
It's okay! Things happen.
