### ISSUE TITLE
RoomFinder: Implementation

### ISSUE THREAD

**Issue by OscarWang114** [wasedatime/wasedatime-web#53]
Implement the RoomFinder component

- [ ] Prepare the classroom data from MongoDB & API
- [ ] Design the UI for classroom searching
- [ ] Implement the Redux or Hook part for connecting the API
- [ ] Connect the API with UI

**Comment by OscarWang114** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RoomFinder: Implementation](https://trello.com/c/FU7BmRjY/5-roomfinder-implementation)

**Comment by AustinZhu** [comment]
#179
