### ISSUE TITLE
Progressive Web App: Implementation

### ISSUE THREAD

**Issue by OscarWang114** [wasedatime/wasedatime-web#54]
- [ ] Understand how to use service workers in create react app
- [ ] Create a simple PWA (refer to issue #3 )
- [ ] Implement caching of the syllabus files in PWA
- [ ] Implement one click and add to home
- [ ] Implement add to home notification

**Comment by OscarWang114** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Progressive Web App: Implementation](https://trello.com/c/MqPs2urd/4-progressive-web-app-implementation)

**Comment by AustinZhu** [comment]
Solved by #123
